_wandb:
    value:
        cli_version: 0.29.0
        e:
            0y51mcgg3f9sojc3p577rbra4u58tj8w:
                executable: /home/pedro/projects/packages/mainboard/.venv/bin/python3
                git:
                    commit: 4a59196ce6a38790049c7d14c43f7a9526669ce0
                    remote: ssh://github.com/phvv-me/mainboard.git
                host: pedro-cvlab
                os: Linux-6.8.0-138-generic-x86_64-with-glibc2.39
                program: <stdin>
                python: CPython 3.14.7
                root: /home/pedro/projects/packages/mainboard
                startedAt: "2026-09-02T23:23:31.649764Z"
                writerId: 0y51mcgg3f9sojc3p577rbra4u58tj8w
        m: []
        python_version: 3.14.7
        t:
            "3":
                - 2
                - 5
                - 14
                - 62
                - 61
            "4": 3.14.7
            "5": 0.29.0
            "12": 0.29.0
            "13": linux-x86_64
