import tomllib
from collections.abc import Iterator
from pathlib import Path

import pytest
from hypothesis import given
from hypothesis import strategies as st

from mainboard import MissionError, Project
from mainboard.engines.compile.generated import GeneratedFiles, Writer
from mainboard.engines.compile.lockfile import Lockfile, Solved

_LOCK = "version: 7\nplatforms:\n- name: linux-64\n"


def _solved(lock: str = _LOCK, *, digest: str = "abc") -> Solved:
    return Solved(solved_from=digest, solved_by="0.79.0", lock=lock)


@pytest.fixture
def files(tmp_path: Path) -> Iterator[Writer]:
    """The workspace sync lock's writer, held for the test."""
    with GeneratedFiles(directory=tmp_path / ".mb").locked() as writer:
        yield writer


@pytest.mark.parametrize(
    "lock",
    [
        pytest.param(_LOCK, id="lf"),
        pytest.param(_LOCK.replace("\n", "\r\n"), id="crlf"),
        pytest.param("version: 7\r\nmixed: true\n", id="mixed-endings"),
        pytest.param("version: 7\nlast: line", id="no-trailing-newline"),
        pytest.param("\nversion: 7\n", id="a-leading-newline-toml-would-trim"),
        pytest.param("quoted: 'x'", id="ends-in-one-quote"),
        pytest.param("quoted: 'x''", id="ends-in-two-quotes"),
        pytest.param("", id="empty"),
        pytest.param("tab:\tsnowman: ☃\n", id="tab-and-non-ascii"),
    ],
)
def test_a_lock_round_trips_byte_for_byte(lock: str, files: Writer, tmp_path: Path) -> None:
    """TOML normalizes the endings inside a literal, so the text is cut from the file's own."""
    lockfile = Lockfile(tmp_path)
    lockfile.put(files, "default", _solved(lock))

    assert Lockfile(tmp_path).get("default") == _solved(lock)
    raw = lockfile.path.read_bytes()
    assert lock.encode() in raw
    parsed = tomllib.loads(raw.decode())
    assert parsed["version"] == 1
    assert parsed["environments"]["default"]["lock"] == lock.replace("\r\n", "\n")


@given(
    st.lists(
        st.sampled_from(["a", " ", "'", "''", '"', "\\", "\n", "\r\n", "\t", "[x]", "é"]),
        max_size=12,
    ).map("".join)
)
def test_any_text_a_literal_can_carry_round_trips(lock: str) -> None:
    """Quotes that never make a delimiter, backslashes and either ending survive untouched."""
    # Rendered, never written, so the root need not exist.
    lockfile = Lockfile(Path("unwritten"))
    if "'''" in lock:
        with pytest.raises(MissionError):
            lockfile.render({"default": _solved(lock)})
        return
    rendered = lockfile.render({"default": _solved(lock)})
    assert Lockfile._texts(rendered) == {"default": lock}
    assert tomllib.loads(rendered)["environments"]["default"]["lock"] == lock.replace("\r\n", "\n")


def test_a_file_names_its_origin_and_keeps_its_sections_sorted(
    files: Writer, tmp_path: Path
) -> None:
    """Sections in name order keep a diff to the environment that moved."""
    (tmp_path / "mainboard.toml").write_text("")
    lockfile = Lockfile(tmp_path)
    for name in ("serving", "default", "cuda.12"):
        lockfile.put(files, name, _solved(f"name: {name}\n"))

    text = lockfile.path.read_text(encoding="utf-8")
    assert text.startswith(
        f"# Generated by {Project().name} from mainboard.toml; commit it. Do not edit.\n"
        "version = 1\n\n"
    )
    headers = [line for line in text.splitlines() if line.startswith("[")]
    assert headers == [
        '[environments."cuda.12"]',
        "[environments.default]",
        "[environments.serving]",
    ]
    assert set(Lockfile(tmp_path).environments()) == {"cuda.12", "default", "serving"}


def test_updating_one_environment_leaves_every_other_section_byte_for_byte(
    files: Writer, tmp_path: Path
) -> None:
    lockfile = Lockfile(tmp_path)
    crlf = _LOCK.replace("\n", "\r\n")
    lockfile.put(files, "serving", _solved(crlf, digest="s"))
    lockfile.put(files, "default", _solved(digest="old"))
    serving = lockfile.path.read_bytes().split(b"[environments.serving]")[1]

    lockfile.put(files, "default", _solved("version: 7\nmoved: true\n", digest="new"))

    assert lockfile.path.read_bytes().split(b"[environments.serving]")[1] == serving
    assert lockfile.get("serving") == _solved(crlf, digest="s")
    assert lockfile.get("default") == _solved("version: 7\nmoved: true\n", digest="new")


def test_a_write_replaces_the_file_whole_or_not_at_all(
    files: Writer, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A crash mid-write leaves the committed lock as it was and no temporary behind."""
    lockfile = Lockfile(tmp_path)
    lockfile.put(files, "default", _solved())
    before = lockfile.path.read_bytes()

    def interrupted(self: Path, target: Path) -> Path:
        raise OSError("interrupted")

    monkeypatch.setattr(Path, "replace", interrupted)
    with pytest.raises(OSError, match="interrupted"):
        lockfile.put(files, "default", _solved(digest="new"))

    assert lockfile.path.read_bytes() == before
    assert sorted(path.name for path in tmp_path.iterdir()) == [".mb", "mb.lock"]


@pytest.mark.parametrize(
    "lock",
    [
        pytest.param("a: '''b'''\n", id="the-delimiter"),
        pytest.param("a\rb\n", id="a-lone-carriage-return"),
        pytest.param("a\x00b\n", id="a-control-character"),
    ],
)
def test_a_lock_a_literal_cannot_carry_is_refused_before_anything_is_written(
    lock: str, files: Writer, tmp_path: Path
) -> None:
    lockfile = Lockfile(tmp_path)
    with pytest.raises(MissionError, match="cannot carry byte for byte, so nothing was written"):
        lockfile.put(files, "default", _solved(lock))
    assert not lockfile.path.exists()


def test_a_workspace_that_never_solved_holds_no_lock(tmp_path: Path) -> None:
    assert Lockfile(tmp_path).environments() == {}
    assert Lockfile(tmp_path).get("default") is None


@pytest.mark.parametrize(
    ("written", "why"),
    [
        pytest.param(b"\xff\xfe", "it is not UTF-8", id="not-utf8"),
        pytest.param(b"version = [", "Restore it from git", id="not-toml"),
        pytest.param(b"version = 2\n", "not a version 1 lock", id="a-newer-format"),
        pytest.param(b"version = 1\nenvironments = 3\n", "not a version 1 lock", id="no-tables"),
        pytest.param(
            b"version = 1\n[environments]\ndefault = 1\n",
            r"\[environments.default\] is not in the shape",
            id="a-section-that-is-not-a-table",
        ),
        pytest.param(
            b'version = 1\n[environments.default]\nlock = "version: 7"\n',
            r"\[environments.default\] is not in the shape",
            id="a-lock-that-is-not-a-literal",
        ),
        pytest.param(
            b"version = 1\n[environments.default]\nsolved_from = 'x'\n",
            r"\[environments.default\] is not in the shape",
            id="a-section-with-no-lock",
        ),
        pytest.param(
            b"version = 1\n[environments.default]\nlock = 'x'\n"
            b"[environments.serving]\nlock = '''\ny'''\n",
            r"\[environments.default\] is not in the shape",
            id="a-lock-that-would-be-read-from-the-next-section",
        ),
    ],
)
def test_a_file_not_in_the_shape_it_is_written_is_refused_with_the_way_back(
    written: bytes, why: str, tmp_path: Path
) -> None:
    (tmp_path / "mb.lock").write_bytes(written)
    with pytest.raises(MissionError, match=why) as refused:
        Lockfile(tmp_path).environments()
    assert "git checkout -- mb.lock" in str(refused.value)
    assert f"{Project().name} install --resolve" in str(refused.value)
