import json
import os
from collections.abc import Mapping
from functools import partial
from pathlib import Path
from typing import TYPE_CHECKING

import pytest
from plumbum import local

from mainboard import MissionError
from mainboard.engines.compile.backend import CommandResult, Pixi, Process

if TYPE_CHECKING:
    from collections.abc import Callable

    from plumbum.commands.base import BaseCommand
    from pytest_subprocess import FakeProcess

    from .support import Record

_FINGERPRINT = ".pixi-environment-fingerprint"
_DAMAGED = "cupy-cuda13x"
_ROOT = "cupy_cuda13x"
_DOTENV_BAT = """@echo off
rem Generated by mainboard's Provisioner (workspace.dotenv = true).
if not exist "values.env" goto :eof
"""


def _cache(pixi: Pixi, *scripts: Path, **variables: str) -> None:
    """Record a Windows activation naming `scripts` and exporting `variables`."""
    pixi.windows_activation_cache.write_text(
        json.dumps(
            {
                "environment_variables": variables,
                "activation_scripts": [str(script) for script in scripts],
            }
        ),
        encoding="utf-8",
    )


@pytest.fixture
def installed(pixi: Pixi) -> Path:
    """An installation of `default` pixi finished and stamped, returning its site-packages."""
    fingerprint = pixi.env_prefix("default") / "conda-meta" / _FINGERPRINT
    fingerprint.parent.mkdir(parents=True)
    fingerprint.write_text("installed\n")
    site_packages = pixi.env_prefix("default") / "lib" / "python3.14" / "site-packages"
    site_packages.mkdir(parents=True)
    pixi.lock.write_text("version: 7\n")
    return site_packages


def test_install_requires_a_lock_unless_resolution_was_requested(
    fp: FakeProcess, pixi: Pixi
) -> None:
    with pytest.raises(MissionError, match=r"pixi.lock is missing.*install --resolve"):
        pixi.install("default")
    assert not fp.calls


@pytest.mark.parametrize(
    ("generated", "rule"),
    [
        pytest.param(None, "--locked", id="nothing-compiled-yet"),
        pytest.param('[dependencies]\nnumpy = "*"\n', "--locked", id="no-source-at-all"),
        pytest.param(
            '[dependencies.demo]\npath = "../demo"\n', "--locked", id="a-path-that-is-not-editable"
        ),
        pytest.param(
            '[[workspace.extra]]\npath = "../demo"\neditable = true\n',
            "--frozen",
            id="an-editable-source-nested-inside-an-array",
        ),
    ],
)
def test_a_mutable_editable_source_is_what_relaxes_locked_into_frozen(
    generated: str | None, rule: str, fp: FakeProcess, pixi: Pixi
) -> None:
    """An editable's code may move without the lock moving."""
    if generated is not None:
        pixi.manifest.write_text(generated)
    pixi.lock.write_text("version: 7\n")
    fp.register([fp.any()], stdout="environment ready\n")

    assert pixi.install("default") is None

    relaxed = "--frozen" if rule == "--locked" else "--locked"
    assert rule in list(fp.calls[0])
    assert relaxed not in list(fp.calls[0])


@pytest.mark.parametrize(
    ("stdout", "stderr", "message"),
    [
        pytest.param(
            "pixi solver context\n",
            "pixi solver failed\n",
            "pixi install",
            id="an-ordinary-failure-stays-an-installation-failure",
        ),
        pytest.param(
            "",
            "the lock file is not up-to-date with the workspace\n",
            r"manifest drifted.*install --resolve",
            id="a-stale-lock-is-refused-with-the-explicit-escape",
        ),
        pytest.param(
            "Pixi task (build): command\n",
            "task says lock file is not up-to-date\n",
            "pixi install",
            id="a-tasks-own-output-is-not-mislabeled-as-drift",
        ),
    ],
)
def test_a_failed_install_reaches_the_callers_output_before_it_is_diagnosed(
    stdout: str,
    stderr: str,
    message: str,
    fp: FakeProcess,
    pixi: Pixi,
    capsys: pytest.CaptureFixture[str],
) -> None:
    pixi.lock.write_text("version: 7\n")
    fp.register([fp.any()], returncode=17, stdout=stdout, stderr=stderr)

    with pytest.raises(MissionError, match=message):
        pixi.install("default")

    assert len(fp.calls) == 1
    assert "--locked" in list(fp.calls[0])
    assert capsys.readouterr() == (stdout, stderr)


@pytest.mark.parametrize(
    ("generated", "verification"),
    [
        pytest.param(
            '[workspace]\nplatforms = ["linux-64"]\n',
            "--locked",
            id="a-freshly-solved-lock-is-verified-locked",
        ),
        pytest.param(
            '[pypi-dependencies.demo]\npath = "../demo"\neditable = true\n',
            "--frozen",
            id="an-editable-source-is-verified-frozen",
        ),
    ],
)
def test_a_resolve_installs_once_more_to_verify_the_lock_it_just_solved(
    generated: str,
    verification: str,
    fp: FakeProcess,
    pixi: Pixi,
    tool_paths: Mapping[str, str],
) -> None:
    pixi.manifest.write_text(generated)
    pixi.lock.write_text("version: 7\n")
    for _ in range(2):
        fp.register([fp.any()], stdout="environment ready\n")

    pixi.install("serving", resolve=True)

    assert len(fp.calls) == 2
    assert " ".join(fp.calls[0]) == (
        f"{tool_paths['pixi']} install --manifest-path {pixi.manifest} -e serving"
    )
    assert verification in list(fp.calls[1])


def test_install_repairs_a_wheel_damaged_underneath_pixi(
    fp: FakeProcess, pixi: Pixi, installed: Path, record: Record, tool_paths: Mapping[str, str]
) -> None:
    root = record(installed, _DAMAGED, roots=f"{_ROOT}\ncupyx\n")
    scope = ["--manifest-path", str(pixi.manifest), "--locked", "-e", "default"]
    fp.register([tool_paths["pixi"], "install", *scope], stdout="environment ready\n")
    fp.register(
        [tool_paths["pixi"], "reinstall", *scope, _DAMAGED],
        stdout="package reinstalled\n",
        callback=lambda process: root.mkdir(),
    )

    pixi.install("default")

    assert len(fp.calls) == 2
    assert list(fp.calls[1]) == [tool_paths["pixi"], "reinstall", *scope, _DAMAGED]


@pytest.mark.parametrize(
    ("finished", "importable"),
    [
        pytest.param(True, True, id="every-package-still-imports"),
        pytest.param(False, False, id="an-interrupted-install-abandoned-the-prefix"),
    ],
)
def test_install_reinstalls_nothing_the_audit_has_no_business_touching(
    finished: bool,
    importable: bool,
    fp: FakeProcess,
    pixi: Pixi,
    installed: Path,
    record: Record,
) -> None:
    root = record(installed, _DAMAGED, roots=f"{_ROOT}\n")
    if importable:
        root.mkdir()
    if not finished:
        (pixi.env_prefix("default") / "conda-meta" / _FINGERPRINT).unlink()
    fp.register([fp.any()], stdout="environment ready\n")

    pixi.install("default")

    assert len(fp.calls) == 1


@pytest.mark.parametrize(
    ("returncode", "message"),
    [
        pytest.param(9, "pixi reinstall", id="the-targeted-reinstall-failed-outright"),
        pytest.param(0, f"{_DAMAGED} stayed incomplete", id="the-reinstall-mended-nothing"),
    ],
)
def test_install_refuses_an_environment_the_repair_left_broken(
    returncode: int,
    message: str,
    fp: FakeProcess,
    pixi: Pixi,
    installed: Path,
    record: Record,
) -> None:
    record(installed, _DAMAGED, roots=f"{_ROOT}\n")
    fp.register([fp.any()], stdout="environment ready\n")
    fp.register([fp.any()], returncode=returncode, stderr="reinstall said so\n")

    with pytest.raises(MissionError, match=message):
        pixi.install("default")


def test_readiness_trusts_the_installation_fingerprint_over_the_directory(
    pixi: Pixi, installed: Path
) -> None:
    assert pixi.ready("default") is True
    assert pixi.ready("serving") is False

    (pixi.env_prefix("default") / "conda-meta" / _FINGERPRINT).unlink()

    assert installed.is_dir()
    assert pixi.ready("default") is False


def test_the_backend_pins_every_call_to_the_workspace_it_owns(pixi: Pixi) -> None:
    assert pixi.scope() == ("--manifest-path", str(pixi.manifest))
    assert pixi.lock == pixi.manifest.with_suffix(".lock")
    assert pixi.env_prefix("serving") == pixi.manifest.parent / ".pixi" / "envs" / "serving"


def test_run_preserves_each_argument_through_pixis_cross_platform_runner(
    fp: FakeProcess,
    pixi: Pixi,
    tool_paths: Mapping[str, str],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr("platform.system", lambda: "Linux")
    fp.register([fp.any()], returncode=7)
    assert pixi.run(("python", "-c", "raise SystemExit(7)"), "serving") == 7
    assert list(fp.calls[0]) == [
        tool_paths["pixi"],
        "run",
        "--manifest-path",
        str(pixi.manifest),
        *("--frozen", "-e", "serving", "python", "-c", "raise SystemExit(7)"),
    ]


def test_windows_runs_explicit_argv_from_the_prefix_with_the_real_home(
    pixi: Pixi,
    installed: Path,
    stub_binary: Callable[[str], str],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    pixi.manifest.write_text(
        """[environments.default]
features = []
[target.win.activation]
scripts = ["dotenv.bat", "unset.bat"]
[target.win.activation.env]
FROM_MANIFEST = "declared"
""",
        encoding="utf-8",
    )
    pixi.manifest.parent.joinpath("values.env").write_text(
        "FROM_DOTENV=loaded\nHOME=C:/wrong\nTO_CLEAR=wrong\n", encoding="utf-8"
    )
    pixi.manifest.parent.joinpath("dotenv.bat").write_text(
        _DOTENV_BAT,
        encoding="utf-8",
    )
    pixi.manifest.parent.joinpath("unset.bat").write_text(
        """@echo off
rem Generated by mainboard from the [env] table.
set TO_CLEAR=
set ALREADY_ABSENT=
""",
        encoding="utf-8",
    )
    _cache(
        pixi,
        pixi.manifest.parent / "dotenv.bat",
        pixi.manifest.parent / "unset.bat",
        FROM_MANIFEST="declared",
        Path=str(local.env["PATH"]),
        SSL_CERT_FILE="C:/prefix/ssl/cacert.pem",
    )
    executable = stub_binary("tectonic")
    prefix_scripts = pixi.env_prefix("default") / "Scripts"
    prefix_scripts.mkdir(parents=True)
    observed: list[tuple[BaseCommand, dict[str, str]]] = []

    def passthrough(command: BaseCommand) -> int:
        observed.append(
            (
                command,
                {
                    name: str(local.env.get(name, ""))
                    for name in (
                        "FROM_DOTENV",
                        "FROM_MANIFEST",
                        "HOME",
                        "PATH",
                        "SSL_CERT_FILE",
                        "TEMP",
                        "TMP",
                        "TO_CLEAR",
                    )
                },
            )
        )
        return 0

    monkeypatch.setattr("platform.system", lambda: "Windows")
    monkeypatch.setattr(Process, "passthrough", passthrough)
    monkeypatch.setenv("HOME", "C:/sandbox/profile")
    monkeypatch.setenv("TO_CLEAR", "inherited")

    with local.env(TO_CLEAR="inherited"):
        assert pixi.run(("tectonic", "--help")) == 0
        assert local.env["TO_CLEAR"] == "inherited"
    assert installed.is_dir()
    command, environment = observed[0]
    assert Path(command.formulate()[0]) == Path(executable)
    assert command.formulate()[1:] == ["--help"]
    assert environment["HOME"] == str(Path.home())
    assert environment["FROM_DOTENV"] == "loaded"
    assert environment["FROM_MANIFEST"] == "declared"
    assert environment["SSL_CERT_FILE"] == "C:/prefix/ssl/cacert.pem"
    assert environment["TO_CLEAR"] == ""
    assert list(map(Path, environment["PATH"].split(os.pathsep)))[:2] == [
        pixi.env_prefix("default"),
        prefix_scripts,
    ]
    assert environment["TEMP"] == environment["TMP"]
    assert Path(environment["TEMP"]).parent != pixi.manifest.parent.parent
    assert Path(environment["TEMP"]).name.startswith("mainboard-run-")
    assert not Path(environment["TEMP"]).exists()
    assert os.environ["HOME"] == "C:/sandbox/profile"


def test_windows_refuses_an_arbitrary_activation_script_instead_of_skipping_it(
    pixi: Pixi,
    installed: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    pixi.manifest.write_text(
        '[target.win.activation]\nscripts = ["custom.bat"]\n', encoding="utf-8"
    )
    script = pixi.manifest.parent / "custom.bat"
    script.write_text("set PROJECT_MODE=unsafe\n")
    _cache(pixi, script)
    monkeypatch.setattr("platform.system", lambda: "Windows")

    assert installed.is_dir()
    with pytest.raises(MissionError, match="cannot reproduce activation script"):
        pixi.run(("tectonic", "--help"))


def test_a_posix_activation_script_is_skipped_on_windows_rather_than_refused(
    pixi: Pixi,
) -> None:
    exported: dict[str, str] = {}
    cleared: set[str] = set()
    pixi._apply_generated_activation(pixi.manifest.parent / "activate.sh", exported, cleared)
    assert (exported, cleared) == ({}, set())


@pytest.mark.parametrize("failed", [False, True])
def test_windows_native_exports_override_activation_without_changing_the_parent(
    pixi: Pixi,
    stub_binary: Callable[[str], str],
    monkeypatch: pytest.MonkeyPatch,
    failed: bool,
) -> None:
    pixi.manifest.write_text("[workspace]\n", encoding="utf-8")
    pixi.windows_activation_cache.write_text("{}", encoding="utf-8")
    stub_binary("python.exe")
    monkeypatch.setattr("platform.system", lambda: "Windows")
    monkeypatch.setattr(Pixi, "ready", lambda self, env: True)
    monkeypatch.setattr(
        Pixi,
        "direct_windows_environment",
        lambda self, env: local.env(PYTHONPATH="activation", PRESERVED="yes"),
    )

    def passthrough(command: BaseCommand) -> int:
        assert command.formulate()[1:] == ["-m", "mainboard.jobs.call", "test_probe.py"]
        assert local.env["PYTHONPATH"] == "C:\\source;C:\\other"
        assert local.env["PRESERVED"] == "yes"
        if failed:
            raise RuntimeError("child failed")
        return 19

    monkeypatch.setattr(Process, "passthrough", passthrough)
    with local.env(PYTHONPATH="parent"):
        command = ("python", "-m", "mainboard.jobs.call", "test_probe.py")
        exports = {"PYTHONPATH": "C:\\source;C:\\other"}
        if failed:
            with pytest.raises(RuntimeError, match="child failed"):
                pixi.run(command, exports=exports)
        else:
            assert pixi.run(command, exports=exports) == 19
        assert local.env["PYTHONPATH"] == "parent"


def test_windows_explicit_argv_requires_a_finished_prefix(
    pixi: Pixi, monkeypatch: pytest.MonkeyPatch
) -> None:
    pixi.manifest.write_text("[workspace]\n", encoding="utf-8")
    _cache(pixi)
    monkeypatch.setattr("platform.system", lambda: "Windows")

    with pytest.raises(MissionError, match="environment 'default' is not installed"):
        pixi.run(("tectonic", "--help"))
    with pytest.raises(MissionError, match="environment 'default' is not installed"):
        pixi.capture(("tectonic", "--help"))


def test_windows_runs_declared_tasks_without_starting_pixis_auth_store(
    fp: FakeProcess,
    pixi: Pixi,
    installed: Path,
    stub_binary: Callable[[str], str],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    pixi.manifest.write_text(
        """[environments.default]
features = ["paper"]
[feature.paper.tasks.paper]
cmd = "tectonic paper.tex"
cwd = "../../.."
""",
        encoding="utf-8",
    )
    _cache(pixi)
    monkeypatch.setattr("platform.system", lambda: "Windows")
    command = stub_binary("tectonic.exe")
    fp.register([fp.any()], returncode=5)

    assert installed.is_dir()
    assert pixi.run(("paper", "--keep-logs")) == 5
    assert list(fp.calls[0]) == [command, "paper.tex", "--keep-logs"]


def test_windows_captures_a_declared_task_without_starting_pixi(
    fp: FakeProcess,
    pixi: Pixi,
    installed: Path,
    stub_binary: Callable[[str], str],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    pixi.manifest.write_text(
        '[tasks.probe]\ncmd = "probe --json"\ncwd = "../../.."\n', encoding="utf-8"
    )
    _cache(pixi)
    monkeypatch.setattr("platform.system", lambda: "Windows")
    command = stub_binary("probe.exe")
    fp.register([fp.any()], stdout='{"ready": true}\n')
    inspect = stub_binary("inspect.exe")
    fp.register([fp.any()], stdout='{"direct": true}\n')

    assert installed.is_dir()
    result = pixi.capture(("probe",))

    assert result.succeeded
    assert result.stdout == '{"ready": true}\n'
    assert list(fp.calls[0]) == [command, "--json"]
    direct = pixi.capture(("inspect", "--json"), timeout=2.0)
    assert direct.stdout == '{"direct": true}\n'
    assert list(fp.calls[1]) == [inspect, "--json"]


def test_windows_capture_shares_one_timeout_across_the_task_graph(
    pixi: Pixi,
    installed: Path,
    stub_binary: Callable[[str], str],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Dependencies consume the selected task's one wall-time budget, as `pixi run` does."""
    pixi.manifest.write_text(
        """[tasks.prepare]
cmd = "prepare"
[tasks.check]
cmd = "check"
depends-on = ["prepare"]
""",
        encoding="utf-8",
    )
    _cache(pixi)
    monkeypatch.setattr("platform.system", lambda: "Windows")
    stub_binary("prepare.exe")
    stub_binary("check.exe")
    readings = iter((10.0, 11.0, 13.0))
    monkeypatch.setattr("mainboard.engines.compile.backend.pixi.monotonic", lambda: next(readings))
    timeouts: list[float | None] = []

    def capture(command: BaseCommand, *, timeout: float | None = None) -> CommandResult:
        timeouts.append(timeout)
        return CommandResult(0, "", "")

    monkeypatch.setattr(Process, "capture", capture)

    assert installed.is_dir()
    assert pixi.capture(("check",), timeout=5.0).succeeded
    assert timeouts == [4.0, 2.0]


def test_windows_caches_pixis_complete_activation_after_provisioning(
    fp: FakeProcess,
    pixi: Pixi,
    tool_paths: Mapping[str, str],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    payload = {
        "environment_variables": {"SSL_CERT_FILE": "C:/prefix/ssl/cacert.pem"},
        "activation_scripts": [],
    }
    monkeypatch.setattr("platform.system", lambda: "Linux")
    pixi.cache_windows_activation("default")
    assert not pixi.windows_activation_cache.exists()
    monkeypatch.setattr("platform.system", lambda: "Windows")
    fp.register([fp.any()], stdout=json.dumps(payload))

    pixi.cache_windows_activation("default")

    assert json.loads(pixi.windows_activation_cache.read_text()) == payload
    assert " ".join(fp.calls[0]) == (
        f"{tool_paths['pixi']} shell-hook --manifest-path {pixi.manifest} "
        "--frozen --json -e default"
    )


def test_the_windows_activation_cache_refuses_missing_stale_and_invalid_state(
    pixi: Pixi,
) -> None:
    with pytest.raises(MissionError, match="Windows activation is not cached"):
        pixi._cached_windows_activation()

    pixi.manifest.write_text("[workspace]\n", encoding="utf-8")
    _cache(pixi)
    # Whole seconds apart, since NTFS keeps a modification time only to 100 ns.
    os.utime(pixi.windows_activation_cache, ns=(1_000_000_000, 1_000_000_000))
    os.utime(pixi.manifest, ns=(2_000_000_000, 2_000_000_000))
    with pytest.raises(MissionError, match="Windows activation changed"):
        pixi._cached_windows_activation()

    pixi.windows_activation_cache.write_text(
        json.dumps({"environment_variables": [], "activation_scripts": {}}), encoding="utf-8"
    )
    with pytest.raises(MissionError, match="Windows activation cache is invalid"):
        pixi._cached_windows_activation()


def test_generated_windows_activation_reports_missing_scripts_and_filters_dotenv_lines(
    pixi: Pixi, monkeypatch: pytest.MonkeyPatch
) -> None:
    exported = {"FROM_PIXI": "kept"}
    cleared: set[str] = set()
    with pytest.raises(MissionError, match="activation script does not exist"):
        pixi._apply_generated_activation(pixi.manifest.parent / "missing.bat", exported, cleared)

    script = pixi.manifest.parent / "dotenv.bat"
    script.write_text(
        _DOTENV_BAT,
        encoding="utf-8",
    )
    pixi._apply_generated_activation(script, exported, cleared)
    assert exported == {"FROM_PIXI": "kept"}

    pixi.manifest.parent.joinpath("values.env").write_text(
        "# comment\nnot-an-assignment\nINHERITED=wrong\nFROM_PIXI=wrong\nNEW=loaded\n",
        encoding="utf-8",
    )
    monkeypatch.setenv("INHERITED", "kept")
    pixi._apply_generated_activation(script, exported, cleared)
    assert exported == {"FROM_PIXI": "kept", "NEW": "loaded"}


def test_a_dotenv_name_is_matched_against_the_activation_the_way_windows_matches_it(
    pixi: Pixi, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`foo=bar` beside a cached `FOO` is skipped, as the case-blind `if not defined` would."""
    monkeypatch.delenv("MIXED", raising=False)
    exported = {"FROM_PIXI": "kept"}
    script = pixi.manifest.parent / "dotenv.bat"
    script.write_text(
        _DOTENV_BAT,
        encoding="utf-8",
    )
    pixi.manifest.parent.joinpath("values.env").write_text(
        "from_pixi=wrong\nmixed=loaded\n", encoding="utf-8"
    )

    pixi._apply_generated_activation(script, exported, set())

    assert exported == {"FROM_PIXI": "kept", "MIXED": "loaded"}


def test_shell_hook_returns_the_activation_script_pixi_prints(
    fp: FakeProcess, pixi: Pixi, tool_paths: Mapping[str, str]
) -> None:
    fp.register(
        [tool_paths["pixi"], "shell-hook", "--frozen", "-s", "bash", "-e", "default"]
        + ["--manifest-path", str(pixi.manifest)],
        stdout='export PATH="/env/bin:$PATH"\n',
    )
    assert pixi.shell_hook() == 'export PATH="/env/bin:$PATH"\n'


def test_activated_puts_the_env_bin_on_path_only_once_it_exists(pixi: Pixi) -> None:
    env_bin = pixi.env_prefix("default") / ("Scripts" if os.name == "nt" else "bin")
    env_bin.mkdir(parents=True)
    with pixi.activated("default"):
        assert str(env_bin) in local.env["PATH"]
    before = local.env["PATH"]
    with pixi.activated("empty-env"):
        assert local.env["PATH"] == before


def test_the_lock_reading_names_every_pinned_package(fp: FakeProcess, pixi: Pixi) -> None:
    pixi.lock.write_text("version: 7\n")
    fp.register([fp.any()], stdout='[{"name": "torch", "version": "2.9.1"}]')
    assert pixi.locked("default") == {"torch": "2.9.1"}
    assert "--frozen" in fp.calls[0]


@pytest.mark.parametrize(
    "solved",
    [
        pytest.param(False, id="nothing-has-been-solved-yet"),
        pytest.param(True, id="the-lock-holds-no-such-environment"),
    ],
)
def test_the_lock_reading_is_empty_when_there_is_nothing_to_read(
    solved: bool, fp: FakeProcess, pixi: Pixi, capsys: pytest.CaptureFixture[str]
) -> None:
    if solved:
        pixi.lock.write_text("version: 7\n")
        fp.register([fp.any()], returncode=1, stderr="unknown environment\n")

    assert pixi.locked("ghost") == {}
    assert capsys.readouterr().err == ""


def test_update_moves_the_lock_and_reports_its_own_failure(fp: FakeProcess, pixi: Pixi) -> None:
    fp.register([fp.any()], stdout="lock updated\n")
    assert pixi.update("default") is None
    fp.register([fp.any()], returncode=1, stderr="could not update\n")
    with pytest.raises(MissionError, match="pixi update"):
        pixi.update("default")


def test_a_restricted_windows_capture_of_a_bare_command_runs_it_from_the_prefix(
    pixi: Pixi,
    installed: Path,
    stub_binary: Callable[[str], str],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    pixi.manifest.write_text("[workspace]\n", encoding="utf-8")
    _cache(pixi, Path=str(local.env["PATH"]))
    monkeypatch.setattr("platform.system", lambda: "Windows")
    command = stub_binary("probe.exe")
    captured: list[list[str]] = []

    def capture(argv: BaseCommand, *, timeout: float | None = None) -> CommandResult:
        captured.append(list(argv.formulate()))
        return CommandResult(0, "{}", "")

    monkeypatch.setattr(Process, "capture", capture)
    assert pixi.capture(("probe", "--json"), "default", timeout=2.0).succeeded
    assert installed.is_dir()
    assert captured == [[command, "--json"]]


def test_run_exports_reach_the_child_through_pixis_runner_and_not_the_parent(
    fp: FakeProcess, pixi: Pixi, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr("platform.system", lambda: "Linux")
    fp.register([fp.any()])
    assert pixi.run(("python", "probe.py"), exports={"CELL": "a b", "SEED": "7"}) == 0
    assert list(fp.calls[0])[-6:] == ["default", "env", "CELL=a b", "SEED=7", "python", "probe.py"]
    assert "CELL" not in os.environ


@pytest.mark.parametrize(
    ("settle", "message"),
    [
        pytest.param(Pixi.solve, "`pixi lock` failed", id="a-solve"),
        pytest.param(
            partial(Pixi.sync, env="default"),
            "could not bring environment 'default' in line with its lock: conflicting",
            id="a-sync-quoting-what-pixi-said",
        ),
    ],
)
def test_a_failed_lock_or_sync_is_raised_rather_than_run_in(
    settle: Callable[[Pixi], None], message: str, fp: FakeProcess, pixi: Pixi
) -> None:
    fp.register([fp.any()], returncode=1, stderr="conflicting requirements\n")
    with pytest.raises(MissionError, match=message):
        settle(pixi)


def test_sync_brings_the_prefix_in_line_with_the_lock_without_solving(
    fp: FakeProcess, pixi: Pixi, tool_paths: Mapping[str, str]
) -> None:
    fp.register([fp.any()])
    pixi.sync("serving")
    assert " ".join(fp.calls[0]) == (
        f"{tool_paths['pixi']} install --manifest-path {pixi.manifest} --frozen -e serving"
    )
