import json
import os
import sys
from collections.abc import Mapping
from pathlib import Path

import pytest

from mainboard.runtime.entry import Entering, Recorded, Refusal, Sourcing, entering
from mainboard.runtime.job import PrefixActivation, WorkspaceActivation

posix_only = pytest.mark.skipif(sys.platform == "win32", reason="POSIX activation is a shell hook")


class Written(Entering):
    """A machine whose activation is already known, so a test sees exactly what was asked."""

    def __init__(self, *, ready: bool = True) -> None:
        self.written = ready
        self.asked: list[tuple[Path, Path, str, str]] = []

    def ready(self, shard: Path, script: Path) -> bool:
        return self.written

    def activated(
        self, base: Mapping[str, str], *, shard: Path, script: Path, env: str, cwd: str
    ) -> dict[str, str]:
        self.asked.append((shard, script, env, cwd))
        return {**base, "ACTIVATED": env}

    def executables(self, prefix: Path) -> list[Path]:
        return [prefix / "bin"]


def built(root: Path, *, stamp: str | None = "a123") -> Path:
    """A built prefix named `a123` under `root`, stamped with `stamp` when there is one."""
    prefix = root / "a123"
    (prefix / ".pixi" / "envs" / "default" / "lib").mkdir(parents=True)
    if stamp is not None:
        (prefix / ".mainboard-prefix").write_text(f"{stamp}\n", encoding="utf-8")
    return prefix


def test_a_finished_prefix_is_entered_with_its_own_libraries_leading(tmp_path: Path) -> None:
    """Thirty two GH200 jobs died importing sqlite3 against `/lib64`'s libstdc++."""
    prefix = built(tmp_path)
    how = Written()
    activation = PrefixActivation(prefix=str(prefix), env="default", refusal="gone")
    entered = activation.entered({"LD_LIBRARY_PATH": "/lib64"}, cwd="/tree", how=how)
    assert how.asked == [(prefix, prefix / "activate.sh", "default", "/tree")]
    assert entered["ACTIVATED"] == "default"
    installed = prefix / ".pixi" / "envs" / "default"
    assert entered["LD_LIBRARY_PATH"].split(os.pathsep) == [str(installed / "lib"), "/lib64"]


@pytest.mark.parametrize(
    ("stamp", "ready"),
    [(None, True), ("other", True), ("a123", False)],
    ids=["never finished", "another environment", "no activation written"],
)
def test_an_unfinished_or_foreign_prefix_is_refused_in_the_dispatchs_own_words(
    tmp_path: Path, stamp: str | None, ready: bool
) -> None:
    prefix = built(tmp_path, stamp=stamp)
    activation = PrefixActivation(prefix=str(prefix), env="default", refusal="rebuild it")
    with pytest.raises(Refusal) as refused:
        activation.entered({}, cwd="/tree", how=Written(ready=ready))
    assert (refused.value.message, refused.value.status) == ("rebuild it", 1)


def test_the_workspace_environment_is_its_activation_then_its_executables_then_nothing(
    tmp_path: Path,
) -> None:
    """A command that quietly runs on the system interpreter is the failure this refuses."""
    installed = tmp_path / ".mainboard" / "envs" / "serving" / ".pixi" / "envs" / "serving"
    activation = WorkspaceActivation(
        script=str(tmp_path / ".mainboard" / "activate-serving.sh"),
        prefix=str(installed),
        refusal="install serving",
    )
    how = Written()
    assert activation.entered({"PATH": "/usr/bin"}, cwd="/tree", how=how)["ACTIVATED"] == "serving"
    assert how.asked == [
        (tmp_path / ".mainboard" / "envs" / "serving", Path(activation.script), "serving", "/tree")
    ]
    with pytest.raises(Refusal, match="install serving"):
        activation.entered({}, cwd="/tree", how=Written(ready=False))
    (installed / "bin").mkdir(parents=True)
    bare = activation.entered({"PATH": "/usr/bin"}, cwd="/tree", how=Written(ready=False))
    assert bare["PATH"].split(os.pathsep) == [str(installed / "bin"), "/usr/bin"]


def test_windows_enters_from_its_record_and_everywhere_else_from_a_shell(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr("platform.system", lambda: "Windows")
    assert isinstance(entering(), Recorded)
    monkeypatch.setattr("platform.system", lambda: "Linux")
    assert isinstance(entering(), Sourcing)


def test_the_windows_record_is_the_activation_with_its_executables_leading(
    tmp_path: Path,
) -> None:
    """Nothing on Windows can source a shell hook, so what pixi recorded is applied directly."""
    shard = tmp_path / "shard"
    prefix = shard / ".pixi" / "envs" / "default"
    (prefix / "Scripts").mkdir(parents=True)
    (shard / "pixi.toml").write_text("[workspace]\n", encoding="utf-8")
    (shard / "unset.bat").write_text(
        "@echo off\nrem Generated by mainboard from the [env] table.\nset CLEARED=\n",
        encoding="utf-8",
    )
    how = Recorded()
    assert not how.ready(shard, shard / "activate.sh")
    (shard / "activation-windows.json").write_text(
        json.dumps(
            {
                "environment_variables": {"CONDA_PREFIX": str(prefix), "PATH": "recorded-path"},
                "activation_scripts": [str(shard / "unset.bat")],
            }
        ),
        encoding="utf-8",
    )
    assert how.ready(shard, shard / "activate.sh")
    entered = how.activated(
        {"CLEARED": "stale", "KEPT": "yes"},
        shard=shard,
        script=shard / "activate.sh",
        env="default",
        cwd=str(tmp_path),
    )
    assert "CLEARED" not in entered and entered["KEPT"] == "yes"
    assert entered["PATH"].split(os.pathsep) == [
        str(prefix),
        str(prefix / "Scripts"),
        "recorded-path",
    ]
    assert how.executables(prefix) == [prefix, prefix / "Scripts", prefix / "Library" / "bin"]


@posix_only
def test_a_shell_sources_the_activation_once_and_reports_only_what_it_built(
    tmp_path: Path,
) -> None:
    """An activation that prints must not corrupt what it hands back, and a shell's own state
    stays behind."""
    script = tmp_path / "activate.sh"
    script.write_text(
        "echo 'activation chatter'\nexport ENTERED=\"$(pwd)\"\ncd /\n", encoding="utf-8"
    )
    how = Sourcing()
    assert how.ready(tmp_path, script) and not how.ready(tmp_path, tmp_path / "missing.sh")
    entered = how.activated(
        {"PATH": os.environ["PATH"], "KEPT": "yes"},
        shard=tmp_path,
        script=script,
        env="default",
        cwd=str(tmp_path),
    )
    assert entered["KEPT"] == "yes"
    assert Path(entered["ENTERED"]).resolve() == tmp_path.resolve()
    assert not {"PWD", "OLDPWD", "SHLVL", "_"} & set(entered)
    assert how.executables(tmp_path) == [tmp_path / "bin"]


@posix_only
@pytest.mark.parametrize("failing", ["return 7", "exit 7", "false"])
def test_a_failed_activation_ends_the_job_with_its_own_status(
    tmp_path: Path, failing: str
) -> None:
    script = tmp_path / "activate.sh"
    script.write_text(f"{failing}\n", encoding="utf-8")
    with pytest.raises(Refusal) as refused:
        Sourcing().activated(
            dict(os.environ), shard=tmp_path, script=script, env="default", cwd=str(tmp_path)
        )
    assert refused.value.message == ""
    assert refused.value.status == (1 if failing == "false" else 7)
