NAME = __name__
__version__ = "0.0.8"

__lazy_modules__ = {
    "mainboard.cpu",
    "mainboard.enums",
    "mainboard.gpu",
    "mainboard.host",
    "mainboard.machine",
    "mainboard.models",
    "mainboard.npu",
    "mainboard.profiling",
    "mainboard.providers",
    "mainboard.unit",
    "mainboard.visual",
}

from .cpu import CPU
from .enums import (
    CmakeBuildType,
    CompilerKind,
    CudaPythonVariant,
    DiskKind,
    Scheduler,
    SystemFamily,
    ToolCategory,
    UnitKind,
    Vendor,
)
from .gpu import GPU
from .host import Host
from .machine import Machine
from .models import (
    Board,
    CgroupMemory,
    Clock,
    ClockInfo,
    CompilerInfo,
    ComputeCapability,
    CpuSnapshot,
    CudaPythonInfo,
    DetectedTool,
    DriveInfo,
    EnergyReading,
    Environment,
    GPUSnapshot,
    HostDisk,
    MachineSnapshot,
    Memory,
    MemoryCard,
    MemoryHardware,
    Meter,
    PartitionInfo,
    PcieInfo,
    ProcessInfo,
    Scratch,
    SystemCompilers,
    ThermalState,
    ThermalTracker,
    ThrottleReason,
    Toolchain,
    ToolProbe,
    UnitSnapshot,
    Utilization,
    meter,
)
from .npu import NPU
from .profiling import (
    Bound,
    Diagnosis,
    KernelStat,
    Profile,
    ProfileReport,
    Profiler,
    ReadResult,
    StorageBandwidth,
    gpu_busy,
    nvme_to_hbm,
    span,
    wait_for_idle,
)
from .profiling import profile_fn as profile
from .providers import (
    AMDGPU,
    AppleGPU,
    AppleNPU,
    IntelGPU,
    IntelNPU,
    NvidiaGPU,
    QualcommGPU,
    QualcommNPU,
)
from .unit import Unit
from .visual import MachineView

__all__ = [
    "NAME",
    "__version__",
    "CPU",
    "GPU",
    "NPU",
    "AMDGPU",
    "AppleGPU",
    "AppleNPU",
    "Board",
    "Bound",
    "CgroupMemory",
    "Clock",
    "ClockInfo",
    "CmakeBuildType",
    "CompilerInfo",
    "CompilerKind",
    "ComputeCapability",
    "CpuSnapshot",
    "CudaPythonInfo",
    "CudaPythonVariant",
    "DetectedTool",
    "Diagnosis",
    "DiskKind",
    "DriveInfo",
    "EnergyReading",
    "Environment",
    "GPUSnapshot",
    "Host",
    "HostDisk",
    "IntelGPU",
    "IntelNPU",
    "KernelStat",
    "Machine",
    "MachineSnapshot",
    "MachineView",
    "Memory",
    "MemoryCard",
    "MemoryHardware",
    "Meter",
    "NvidiaGPU",
    "PartitionInfo",
    "ProfileReport",
    "Profile",
    "Profiler",
    "PcieInfo",
    "ProcessInfo",
    "QualcommGPU",
    "QualcommNPU",
    "ReadResult",
    "Scheduler",
    "Scratch",
    "StorageBandwidth",
    "SystemCompilers",
    "SystemFamily",
    "ThermalState",
    "ThermalTracker",
    "ThrottleReason",
    "ToolCategory",
    "ToolProbe",
    "Toolchain",
    "Unit",
    "UnitKind",
    "UnitSnapshot",
    "Utilization",
    "Vendor",
    "gpu_busy",
    "meter",
    "nvme_to_hbm",
    "profile",
    "span",
    "wait_for_idle",
]
