import hashlib
import json
import tomllib
from typing import TYPE_CHECKING

from ...core import MissionError, Project
from .pixi_manifest import PixiManifest
from .state import SyncState

if TYPE_CHECKING:
    from pathlib import Path

    from ...manifest import Manifest, Scope
    from .backend import Pixi
    from .ecosystems import SecondStage
    from .generated import Writer
    from .toml import Toml

# Freshness truth lives in one atomically-replaced state file (see `state.SyncState`), and the
# compiler reads a coherent snapshot and writes the whole next snapshot in a single replace,
# never a partial marker.

_DOTENV = "dotenv.sh"
_DOTENV_SH = """#!/usr/bin/env bash
# Generated by mainboard's Provisioner (workspace.dotenv = true). Do not edit by hand.
# A variable already exported in the shell wins over one in `.env`, which only fills gaps.
snapshot="$(mktemp)"
export -p > "$snapshot"
set -a
[ -f "../.env" ] && . "../.env"
set +a
. "$snapshot" 2>/dev/null || true
rm -f "$snapshot"
unset snapshot
"""


class Compiler:
    """Turns a manifest into the generated `.mainboard/` env, and says when that env is stale.

    A compile writes the pixi manifest, the dotenv loader, whatever the second-stage
    toolchains install from, and the digest marker that later calls compare against. Nothing
    here provisions anything, so the same write runs under `Provisioner.activated`'s short
    lock and inside `provision`'s longer one.
    """

    def __init__(
        self, root: Path, manifest: Manifest, out: Path, pixi: Pixi, stage: SecondStage
    ) -> None:
        self.root = root
        self.manifest = manifest
        self.out = out
        self.pixi = pixi
        self.stage = stage

    def digest(self) -> str:
        """A content hash of the manifest, the key that decides whether a compile is current."""
        payload = self.manifest.model_dump(mode="json", round_trip=True)
        canonical = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
        return hashlib.sha256(canonical).hexdigest()

    def install_locked(self, files: Writer, env: str, *, resolve: bool) -> None:
        """Install ``env`` and bless its lock, in the one order that keeps the state honest.

        A stale flag refuses the install outright unless this machine may solve, and it is
        cleared only after a solve returned without raising, so a failed install can never
        leave a lock that nothing on disk vouches for looking fresh.
        """
        state = SyncState.load(self.out)
        if state.resolution_stale and not resolve:
            raise MissionError(
                "pixi.lock no longer matches the resolution inputs. Run "
                "`Provisioner.provision(resolve=True)` on a solve-capable machine."
            )
        self.pixi.install(env, resolve=resolve)
        if state.resolution_stale:
            self.__persist_state(files, state.model_copy(update={"resolution_stale": False}))

    def stale(self, env: str = "default") -> bool:
        """Whether ``env``'s generated env predates the current manifest content.

        True once a compile exists but the manifest has changed since it ran, so a caller can
        recompile before activating rather than serve env vars and deps from a stale
        `.mainboard/`. A workspace with nothing compiled yet is not stale, since first
        provisioning is `provision`'s job, not `activated`'s.
        """
        if not self.pixi.manifest.exists():
            return False
        return SyncState.load(self.out).envs.get(env) != self.digest()

    def write(self, files: Writer, env: str) -> None:
        """Write every generated file for ``env``, through the writer the sync lock hands out."""
        # The digest is taken before the translation, so an edit landing mid-compile leaves
        # the workspace stale rather than blessing output built from content nobody compiled.
        source_digest = self.digest()
        project = Project()
        compiled = PixiManifest.from_manifest(self.manifest, project_name=project.name).to_toml()
        resolution_digest = self._resolution_digest()
        state = SyncState.load(self.out)
        if self._resolution_drifted(state, compiled, resolution_digest=resolution_digest):
            state = state.model_copy(update={"resolution_stale": self.pixi.lock.exists()})
        self._write_generated_files(files, compiled=compiled, env=env)
        # A crash anywhere above must leave the workspace stale, so the state snapshot only
        # lands once every file compiled from this manifest is already on disk, and it lands
        # as ONE atomic replace carrying digest, inputs, and stale flag together.
        self.__persist_state(
            files,
            state.model_copy(
                update={
                    "envs": {**state.envs, env: source_digest},
                    "resolution_inputs": resolution_digest,
                }
            ),
        )

    @staticmethod
    def _resolution_manifest(text: str) -> dict[str, Toml]:
        """Return generated Pixi data that can affect dependency resolution."""
        document = tomllib.loads(text)
        document.pop("tasks", None)
        return document

    def _local_python_projects(self) -> list[str]:
        """Every declared local Python project path across every active scope.

        Only the `python` ecosystem is considered: pixi resolves against a path dependency's
        own `pyproject.toml`, and that is the one ecosystem this port translates.
        """
        scopes: list[Scope] = [self.manifest, self.manifest.dev, *self.manifest.on.values()]
        for env in self.manifest.envs.values():
            scopes.extend([env, *env.on.values()])
        python_deps = (
            spec
            for scope in scopes
            if (python := scope.toolchains().get("python"))
            for spec in python.all_deps().values()
        )
        return sorted(
            {
                path
                for spec in python_deps
                if spec.is_path and isinstance(path := (spec.model_extra or {}).get("path"), str)
            }
        )

    def _resolution_digest(self) -> str:
        """Hash local Python project metadata that can change without changing the manifest."""
        digest = hashlib.sha256()
        for declared in self._local_python_projects():
            project = self.root / declared / "pyproject.toml"
            digest.update(declared.encode())
            try:
                digest.update(project.read_bytes())
            except FileNotFoundError:
                digest.update(b"\0")
        return digest.hexdigest()

    def _resolution_drifted(
        self, state: SyncState, compiled: str, *, resolution_digest: str
    ) -> bool:
        """Whether ``compiled`` or its resolution inputs differ from what was generated last.

        A generated file that is missing counts as drift, since nothing on disk can vouch for
        the lock that is already there.
        """
        try:
            existing = self.pixi.manifest.read_text(encoding="utf-8")
        except FileNotFoundError:
            existing = compiled
        if self._resolution_manifest(existing) != self._resolution_manifest(compiled):
            return True
        return state.resolution_inputs != resolution_digest

    def _write_generated_files(self, files: Writer, *, compiled: str, env: str) -> None:
        """Write the compiled pixi manifest, the dotenv loader, and the second-stage files.

        pixi is handed conda and Python (see `pixi_manifest.dependency_tables`); every other
        declared ecosystem generates whatever its own manager reads through the second stage.
        """
        files.write(self.pixi.manifest, compiled)
        if self.manifest.workspace.dotenv:
            files.write(self.out / _DOTENV, _DOTENV_SH)
        self.stage.generate(files, env)

    def __persist_state(self, files: Writer, state: SyncState) -> None:
        """Replace the whole state snapshot in one atomic write."""
        files.write(SyncState.path(self.out), state.render())
