# THE SOLVE IS SOURCE, NOT CACHE. Each environment's pixi.lock used to live only in the ignored
# state directory, beside the `state.toml` that vouched for it, and a wiped disk (2026-09) left a
# single surviving copy on a host. Every host installs a lock and every prefix is addressed by
# one, so the solve now lives in one committed file at the workspace root, a section per
# environment, and the state directory's copy is materialized from it.
#
# The lock text rides byte for byte in a TOML multi-line literal string. A TOML reader normalizes
# the line endings inside one, so the text is cut from the file's own characters and only checked
# against what the reader parsed.

import json
import re
import tomllib
from typing import TYPE_CHECKING

from patos import FrozenModel

from ...core import MissionError, Project

if TYPE_CHECKING:
    from pathlib import Path

    from .generated import Writer

# The format this release reads and writes; a file claiming another is refused, never guessed at.
VERSION = 1

_DELIMITER = "'''"

# What an environment name may be written as unquoted in a table header.
_BARE = re.compile(r"[A-Za-z0-9_-]+")

# A section's header, its name bare or quoted (`environment_segment` allows dots), and its lock:
# the literal after the opening line, up to a delimiter no further quote follows, the one or two
# quotes a literal may end in kept. Both anchored to a line start and scanned in order, so the
# text of one lock never reads as the next header.
_SECTION = re.compile(r'^\[environments\.([A-Za-z0-9_-]+|"[^"\\\r\n]*")\]\r?\n', re.MULTILINE)
_LOCK = re.compile(r"^lock = '''\r?\n(.*?'{0,2})'''(?!')", re.MULTILINE | re.DOTALL)

# What a TOML literal string cannot hold once CRLF pairs are taken out: every control character
# but the tab and the newline, a lone carriage return among them.
_UNCARRIABLE = re.compile(r"[\x00-\x08\x0b-\x1f\x7f]")


class Solved(FrozenModel):
    """One environment's solve as committed.

    solved_from: the resolution digest (`Compiler.resolution_digest`) the lock answers to.
    solved_by: the pixi version that wrote the lock.
    lock: the pixi.lock text, exactly as pixi wrote it.
    """

    solved_from: str
    solved_by: str
    lock: str


class Lockfile:
    """The committed lock at a workspace root: one section per environment, sorted by name."""

    def __init__(self, root: Path) -> None:
        project = Project()
        self.path = project.lock(root)
        self.manifest = project.manifest(root).name

    def environments(self) -> dict[str, Solved]:
        """Every environment's solve, none when the file does not exist yet."""
        try:
            raw = self.path.read_bytes().decode("utf-8")
        except FileNotFoundError:
            return {}
        except UnicodeDecodeError as error:
            raise self._malformed(f"it is not UTF-8 ({error.reason})") from error
        try:
            parsed = tomllib.loads(raw)
        except tomllib.TOMLDecodeError as error:
            raise self._malformed(str(error)) from error
        tables = parsed.get("environments", {})
        if parsed.get("version") != VERSION or not isinstance(tables, dict):
            raise self._malformed(
                f"it is not a version {VERSION} lock, which is all this release reads"
            )
        texts = self._texts(raw)
        found: dict[str, Solved] = {}
        for name, table in tables.items():
            text = texts.get(name)
            if (
                not isinstance(table, dict)
                or text is None
                or text.replace("\r\n", "\n") != table.get("lock")
            ):
                raise self._malformed(f"[environments.{name}] is not in the shape it is written")
            found[name] = Solved(
                solved_from=str(table.get("solved_from", "")),
                solved_by=str(table.get("solved_by", "")),
                lock=text,
            )
        return found

    def get(self, environment: str) -> Solved | None:
        """`environment`'s committed solve, None when the file holds none."""
        return self.environments().get(environment)

    def put(self, files: Writer, environment: str, solved: Solved) -> None:
        """Record `environment`'s solve atomically, every other section kept as it reads.

        files: the writer holding the workspace sync lock, which serializes every
            read-modify-write of this one file across environments.
        """
        environments = self.environments()
        environments[environment] = solved
        files.write(self.path, self.render(environments))

    def render(self, environments: dict[str, Solved]) -> str:
        """The file's text: a header, the version, then each environment in name order."""
        parts = [
            f"# Generated by {Project().name} from {self.manifest}; commit it. Do not edit.\n",
            f"version = {VERSION}\n",
        ]
        for name in sorted(environments):
            solved = environments[name]
            parts.append(
                f"\n[environments.{_key(name)}]\n"
                f"solved_from = {json.dumps(solved.solved_from)}\n"
                f"solved_by = {json.dumps(solved.solved_by)}\n"
                f"lock = {_DELIMITER}\n{self._carriable(name, solved.lock)}{_DELIMITER}\n"
            )
        return "".join(parts)

    def _carriable(self, environment: str, text: str) -> str:
        """`text`, refused when a TOML literal string cannot carry it byte for byte."""
        if _DELIMITER in text or _UNCARRIABLE.search(text.replace("\r\n", "")):
            raise MissionError(
                f"the lock solved for {environment!r} holds {_DELIMITER} or a control character, "
                f"which {self.path.name} cannot carry byte for byte, so nothing was written"
            )
        return text

    @staticmethod
    def _texts(raw: str) -> dict[str, str]:
        """Each section's lock, cut from the file's own characters so its line endings survive."""
        texts: dict[str, str] = {}
        position = 0
        while (header := _SECTION.search(raw, position)) and (
            lock := _LOCK.search(raw, header.end())
        ):
            texts[_name(header.group(1))] = lock.group(1)
            position = lock.end()
        return texts

    def _malformed(self, why: str) -> MissionError:
        return MissionError(
            f"{self.path} cannot be read: {why}. Restore it from git (`git checkout -- "
            f"{self.path.name}`), or solve it again with `{Project().name} install --resolve`."
        )


def _key(name: str) -> str:
    """`name` as a table-header key, quoted when it holds more than a bare key may."""
    return name if _BARE.fullmatch(name) else json.dumps(name)


def _name(key: str) -> str:
    """The environment a table-header key names."""
    return str(json.loads(key)) if key.startswith('"') else key
