import tomllib
from typing import TYPE_CHECKING, Self

from patos import FrozenModel

if TYPE_CHECKING:
    from pathlib import Path

# The single freshness-truth file: one file, one atomic replace, one coherent snapshot per
# read, so concurrent processes never see a torn multi-file protocol.
_FILENAME = "state.toml"


class SyncState(FrozenModel):
    """The compile-freshness snapshot of one generated environment shard.

    `environment` names the logical Mainboard environment the directory belongs to.
    `compiled_from` is that environment's selected-manifest digest, and `solved_from` is the
    resolution digest the lock beside it was solved from. The latter is written only when a
    solve succeeds, so staleness is a comparison against the lock rather than a flag somebody
    has to remember to clear. Keeping all four beside one shard means no environment can
    accidentally vouch for another one's generated files or lock.

    `solved_by` is the pixi that produced the lock, recorded beside the blessing because a lock
    is pixi's file rather than this package's and each version writes some of it differently.
    The fleet is pinned to one pixi (`backend.PIXI_VERSION`) so that never varies; this is what
    lets a machine say out loud that a lock in front of it came from another one.
    """

    environment: str = ""
    compiled_from: str = ""
    solved_from: str = ""
    solved_by: str = ""

    @staticmethod
    def path(out: Path) -> Path:
        """Where the state file lives under generated dir ``out``."""
        return out / _FILENAME

    @classmethod
    def load(cls, out: Path) -> Self:
        """The state under generated dir ``out``, empty when absent or unreadable.

        Empty reads as stale everywhere, the safe direction, the next write recomputes every
        digest and re-derives the lock-stale flag from the drift check, so no marker
        archaeology is ever needed.
        """
        try:
            data = tomllib.loads(cls.path(out).read_text(encoding="utf-8"))
        except FileNotFoundError, tomllib.TOMLDecodeError:
            return cls()
        return cls(
            environment=str(data.get("environment", "")),
            compiled_from=str(data.get("compiled_from", "")),
            solved_from=str(data.get("solved_from", "")),
            solved_by=str(data.get("solved_by", "")),
        )

    def render(self) -> str:
        """The TOML text of this state, a fixed tiny schema rendered by hand."""
        lines = [
            "# Generated by mainboard: the single compile-freshness truth, written",
            "# atomically under the workspace sync lock. Do not edit.",
            f'environment = "{self.environment}"',
            f'compiled_from = "{self.compiled_from}"',
            f'solved_from = "{self.solved_from}"',
            f'solved_by = "{self.solved_by}"',
        ]
        return "\n".join(lines) + "\n"
